name: zServers
main: me.z609.servers.zServers
version: 1.0
description: Containerize each of your Minecraft server instances, including full modular support.
softdepend: [TimoCloud,ViaVersion]
authors: [z609]
website: https://www.z609.me/zservers
commands:
  server:
    usage: /server [serverName]
    description: Connect to a different server.
  find:
    usage: /find <playerName>
    description: Find the location of a player on the network.
  glist:
    usage: /glist
    description: List of all players globally.
  send:
    usage: /send <target> [targetServer]
    description: Move players around the network.
  hub:
    usage: /hub
    description: Return to the hub.
    aliases: [lobby]
  whereami:
    usage: /whereami
    description: Find out where you are on the network.
  remoteExec:
    usage: /remoteExec <serverName> <command> [args]
    description: Use a zServer command from the console.